//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCv
    {
        public int ic_id { get; set; }
        public string ic_name { get; set; }
        public string ic_mid { get; set; }
        public string ic_content { get; set; }
        public Nullable<int> ic_fakeid { get; set; }
        public Nullable<int> ic_theme_id { get; set; }
        public Nullable<int> ic_usid { get; set; }
        public Nullable<int> ic_stt { get; set; }
        public string ic_enddate { get; set; }
        public string ic_todate { get; set; }
        public string ic_fake { get; set; }
    }
}
