//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Groups = new HashSet<Group>();
            this.SubmitCvs = new HashSet<SubmitCv>();
            this.SubmitJobs = new HashSet<SubmitJob>();
        }
    
        public int job_id { get; set; }
        public string job_title { get; set; }
        public string job_addpress { get; set; }
        public Nullable<int> job_amout { get; set; }
        public Nullable<int> wp_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<bool> job_sex { get; set; }
        public Nullable<int> exp_id { get; set; }
        public string job_payend { get; set; }
        public string job_paystart { get; set; }
        public Nullable<System.DateTime> job_datedeline { get; set; }
        public string job_name { get; set; }
        public string job_phone { get; set; }
        public string job_describe { get; set; }
        public string job_request { get; set; }
        public string job_right { get; set; }
        public Nullable<bool> job_active { get; set; }
        public Nullable<bool> job_option { get; set; }
        public Nullable<System.DateTime> job_datecreate { get; set; }
        public Nullable<System.DateTime> job_dateupdate { get; set; }
        public Nullable<bool> job_bin { get; set; }
        public Nullable<int> job_view { get; set; }
        public Nullable<int> user_id { get; set; }
        public string job_key { get; set; }
        public string job_textprice { get; set; }
    
        public virtual Exp Exp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        public virtual TypeJob TypeJob { get; set; }
        public virtual User User { get; set; }
        public virtual WorkPlace WorkPlace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmitCv> SubmitCvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmitJob> SubmitJobs { get; set; }
    }
}
