//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataQuickJobEntities : DbContext
    {
        public DataQuickJobEntities()
            : base("name=DataQuickJobEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Category> Categorys { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<Cv> Cvs { get; set; }
        public virtual DbSet<Exp> Exps { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<ItemCv> ItemCvs { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Pakage> Pakages { get; set; }
        public virtual DbSet<Provice> Provices { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SubmitCv> SubmitCvs { get; set; }
        public virtual DbSet<SubmitJob> SubmitJobs { get; set; }
        public virtual DbSet<Theme> Themes { get; set; }
        public virtual DbSet<TypeJob> TypeJobs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Version> Versions { get; set; }
        public virtual DbSet<ViewCv> ViewCvs { get; set; }
        public virtual DbSet<Word> Words { get; set; }
        public virtual DbSet<WorkPlace> WorkPlaces { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
