//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmitCv
    {
        public int sb_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> job_id { get; set; }
        public Nullable<System.DateTime> sb_datecreate { get; set; }
        public Nullable<int> sb_active { get; set; }
        public string sb_notecandidate { get; set; }
        public string sb_noteemployer { get; set; }
        public Nullable<System.DateTime> sb_update { get; set; }
        public Nullable<int> cv_id { get; set; }
    
        public virtual Cv Cv { get; set; }
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
