//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Bills = new HashSet<Bill>();
            this.Cvs = new HashSet<Cv>();
            this.Groups = new HashSet<Group>();
            this.Jobs = new HashSet<Job>();
            this.News = new HashSet<News>();
            this.SubmitCvs = new HashSet<SubmitCv>();
            this.SubmitJobs = new HashSet<SubmitJob>();
            this.ViewCvs = new HashSet<ViewCv>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public int user_id { get; set; }
        public string user_email { get; set; }
        public string user_pass { get; set; }
        public Nullable<bool> user_active { get; set; }
        public Nullable<bool> user_option { get; set; }
        public Nullable<System.DateTime> user_datecreate { get; set; }
        public Nullable<System.DateTime> user_dateupdate { get; set; }
        public string user_img { get; set; }
        public Nullable<bool> user_sex { get; set; }
        public Nullable<System.DateTime> user_birth { get; set; }
        public string user_favourite { get; set; }
        public Nullable<int> role_id { get; set; }
        public string user_name { get; set; }
        public string user_phone { get; set; }
        public string employer_company { get; set; }
        public Nullable<int> provice_id { get; set; }
        public string employer_banner { get; set; }
        public string employer_logo { get; set; }
        public string employer_introduce { get; set; }
        public string employer_favourite { get; set; }
        public Nullable<int> employer_amount { get; set; }
        public string user_note { get; set; }
        public Nullable<bool> employer_pageload { get; set; }
        public string employer_youtube { get; set; }
        public string user_key { get; set; }
        public Nullable<int> wp_id { get; set; }
        public string employer_addpress { get; set; }
        public Nullable<int> version_id { get; set; }
        public Nullable<System.DateTime> user_deadline { get; set; }
        public Nullable<int> employer_amoutjob { get; set; }
        public Nullable<bool> user_bin { get; set; }
        public Nullable<int> candidate_amoutcv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cv> Cvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<News> News { get; set; }
        public virtual Provice Provice { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmitCv> SubmitCvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmitJob> SubmitJobs { get; set; }
        public virtual Version Version { get; set; }
        public virtual WorkPlace WorkPlace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViewCv> ViewCvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
